services:
  exporter:
    build: ./exporter
    environment:
      INVESTMENT_START_DATE: '2020-01-01'
      SCRAPER_ENDPOINT: "scraper:50051"
    depends_on:
      scraper:
        condition: service_started
    ports:
      - 8080:8080
    restart: on-failure

  scraper:
    build: ./scraper
    env_file: "./scraper-env"
    volumes:
      - "./scraper/downloaded:/csv"
    environment:
      DOWNLOAD_DIR: '/csv'
      CACHE_TTL_SECOND: '-1'
      CACHE_CLEAR_ON_START: 'False'
    ports:
      - 8000:8000
      - 50051:50051
