# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rakuten-security-scraper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1erakuten-security-scraper.proto\" \n\x1eListWithdrawalHistoriesRequest\"F\n\x1fListWithdrawalHistoriesResponse\x12#\n\x07history\x18\x01 \x03(\x0b\x32\x12.WithdrawalHistory\"Q\n\x11WithdrawalHistory\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t2x\n\x16RakutenSecurityScraper\x12^\n\x17ListWithdrawalHistories\x12\x1f.ListWithdrawalHistoriesRequest\x1a .ListWithdrawalHistoriesResponse\"\x00\x42\x36Z4github.com/Kotaro7750/rakuten-security-exporter/mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rakuten_security_scraper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/Kotaro7750/rakuten-security-exporter/main'
  _globals['_LISTWITHDRAWALHISTORIESREQUEST']._serialized_start=34
  _globals['_LISTWITHDRAWALHISTORIESREQUEST']._serialized_end=66
  _globals['_LISTWITHDRAWALHISTORIESRESPONSE']._serialized_start=68
  _globals['_LISTWITHDRAWALHISTORIESRESPONSE']._serialized_end=138
  _globals['_WITHDRAWALHISTORY']._serialized_start=140
  _globals['_WITHDRAWALHISTORY']._serialized_end=221
  _globals['_RAKUTENSECURITYSCRAPER']._serialized_start=223
  _globals['_RAKUTENSECURITYSCRAPER']._serialized_end=343
# @@protoc_insertion_point(module_scope)
