# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rakuten_security_scraper_pb2 as rakuten__security__scraper__pb2


class RakutenSecurityScraperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListWithdrawalHistories = channel.unary_unary(
                '/RakutenSecurityScraper/ListWithdrawalHistories',
                request_serializer=rakuten__security__scraper__pb2.ListWithdrawalHistoriesRequest.SerializeToString,
                response_deserializer=rakuten__security__scraper__pb2.ListWithdrawalHistoriesResponse.FromString,
                )
        self.ListDividendHistories = channel.unary_unary(
                '/RakutenSecurityScraper/ListDividendHistories',
                request_serializer=rakuten__security__scraper__pb2.ListDividendHistoriesRequest.SerializeToString,
                response_deserializer=rakuten__security__scraper__pb2.ListDividendHistoriesResponse.FromString,
                )


class RakutenSecurityScraperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListWithdrawalHistories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDividendHistories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RakutenSecurityScraperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListWithdrawalHistories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWithdrawalHistories,
                    request_deserializer=rakuten__security__scraper__pb2.ListWithdrawalHistoriesRequest.FromString,
                    response_serializer=rakuten__security__scraper__pb2.ListWithdrawalHistoriesResponse.SerializeToString,
            ),
            'ListDividendHistories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDividendHistories,
                    request_deserializer=rakuten__security__scraper__pb2.ListDividendHistoriesRequest.FromString,
                    response_serializer=rakuten__security__scraper__pb2.ListDividendHistoriesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RakutenSecurityScraper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RakutenSecurityScraper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListWithdrawalHistories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RakutenSecurityScraper/ListWithdrawalHistories',
            rakuten__security__scraper__pb2.ListWithdrawalHistoriesRequest.SerializeToString,
            rakuten__security__scraper__pb2.ListWithdrawalHistoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListDividendHistories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RakutenSecurityScraper/ListDividendHistories',
            rakuten__security__scraper__pb2.ListDividendHistoriesRequest.SerializeToString,
            rakuten__security__scraper__pb2.ListDividendHistoriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
